### ISSUE TITLE
Issue with 2.0 branch

### ISSUE THREAD

**Issue by kiddten** [kiddick/yappi#1]
Error message:

```
2016-05-16 20:53:42,915 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "lib\site-packages\telegram\ext\dispatcher.py", line 180, in processUpdate
    handler.handle_update(update, self)
  File "lib\site-packages\telegram\ext\commandhandler.py", line 62, in handle_update
    self.callback(dispatcher.bot, update, **optional_args)
TypeError: handle_message() takes exactly 3 arguments (2 given)
```

**Comment by kiddten** [comment]
Fixed
https://github.com/kiddick/yappi/commit/b5cb8fd09e3da49bd6197cfb87a5ea998d7b8d16
